worker_processes 4;

events { worker_connections 1024; }

http {
	server {
		listen 3000;

		location / {
			default_type  application/octet-stream;
			include /etc/nginx/mime.types;

        	root /var/www;
        	try_files $uri $uri/ /index.html;
    	}
	}
}