worker_processes 4;

events { worker_connections 1024; }

http {
	server {
		listen 80;

		location /api/ { 
			proxy_pass http://deliverymanagement_backend:8080/api/;
		}

		location /images/ {
			proxy_pass http://deliverymanagement_backend:8080/images/;
		}

		location / {
			proxy_pass http://deliverymanagement_frontend:3000/;
    	}
	}
}