name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export JWT_SECRETKEY="${{ secrets.JWT_SECRETKEY }}"
            export SEED_TEST_DATA="${{ vars.SEED_TEST_DATA }}"

            if [ ! -d "${{ github.event.repository.name }}" ]; then
              echo "Cloning repository."
              git clone git@github.com:${{ github.repository }}.git
            fi

            cd ${{ github.event.repository.name }}
            echo "Pulling changes."
            git pull origin main --rebase

            if [ -d "./app/backend/backend/wwwroot/images/test" ]; then 
              echo "Copying test data."
              mkdir -p ./.containers/backend/images/test
              cp -r ./app/backend/backend/wwwroot/images/test/* ./.containers/backend/images/test/
            else 
              echo "Test data not found."
            fi

            echo "Stopping compose."
            docker compose down --rmi all

            echo "Running compose."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

            echo "Finished."
